### ISSUE TITLE
Exception when building 

### ISSUE THREAD

**Issue by 23min** [boot-clj/boot#123]
Hi, newcomer to boot here.

Just checked out a minimal project template: https://github.com/pandeiro/jamal

```
$ boot cljs -s
Compiling boot-cljs-main.js...
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
    data: {:file
           "../var/folders/z9/c5ft2h457g5fmsl3v1zt1lm80000gn/T/boot.user849630962410923277.clj",
           :line 11}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
     java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
```

Also, I had to create the target directory manually. This should be handled by boot.

**Comment by micha** [comment]
Can you please paste the output of `boot -h |head -n 3`? That will show the version of boot you're using.

**Comment by micha** [comment]
Also, if you could paste the output of `boot -vv cljs -s` that would help. We could see the complete stack trace that way.

**Comment by 23min** [comment]
OSX Mavericks, Java 8.

```
$ boot -h |head -n 3
Boot App Version: 2.0.0-rc9
Boot Lib Version: 2.0.0-rc9
Clojure Version:  1.6.0
             clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
    data: {:file
           "../var/folders/z9/c5ft2h457g5fmsl3v1zt1lm80000gn/T/boot.user7133766579534772703.clj",
           :line 11}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
     java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
                                ...                                        
         boot.file/tree-for/iter/fn                          file.clj:  132
                                ...                                        
                   clojure.core/seq                          core.clj:  133
  clojure.core.protocols/seq-reduce                     protocols.clj:   30
          clojure.core.protocols/fn                     protocols.clj:   54
        clojure.core.protocols/fn/G                     protocols.clj:   13
                clojure.core/reduce                          core.clj: 6289
                 boot.file/tree-for                          file.clj:  131
                                ...                                        
                    boot.file/sync!                          file.clj:  162
                                ...                                        
                 clojure.core/apply                          core.clj:  628
       boot.core/run-tasks/sync!/fn                          core.clj:  632
          boot.core/run-tasks/sync!                          core.clj:  631
             boot.core/run-tasks/fn                          core.clj:  637
     boot.task.built-in/fn/fn/fn/fn                      built_in.clj:   26
                boot.core/run-tasks                          core.clj:  637
                                ...                                        
               boot.user/eval347/fn  boot.user7133766579534772703.clj:   13
clojure.core/binding-conveyor-fn/fn                          core.clj: 1910
```
=============================
```
$ boot -vv cljs -s
registering src [:create :modify]
sending change event
watch service closed
registering src [:create :modify]
registering conf [:create :modify]
registering html [:create :modify]
sending change event
Compiling boot-cljs-main.js...
CLJS options:
{:source-map-path "out",
 :output-to
 "/Users/peterbru/.boot/tmp/Users/peterbru/my-app/2jg/re63ra/boot-cljs-main.js",
 :source-map
 "/Users/peterbru/.boot/tmp/Users/peterbru/my-app/2jg/re63ra/boot-cljs-main.js.map",
 :libs [],
 :externs [],
 :preamble [],
 :output-dir
 "/Users/peterbru/.boot/tmp/Users/peterbru/my-app/2jg/re63ra/out",
 :optimizations :none}

clojure.lang.ExceptionInfo: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet {:file "../var/folders/z9/c5ft2h457g5fmsl3v1zt1lm80000gn/T/boot.user533829959110297580.clj", :line 11}
        at clojure.core$ex_info.invoke(core.clj:4403)
        at boot.main$_main$fn__881.invoke(main.clj:148)
        at boot.main$_main.invoke(main.clj:139)
        at clojure.lang.Var.invoke(Var.java:394)
        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:138)
        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:129)
        at boot.App.runBoot(App.java:227)
        at boot.App.main(App.java:325)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at clojure.core$deref_future.invoke(core.clj:2180)
        at clojure.core$future_call$reify__6320.deref(core.clj:6420)
        at clojure.core$deref.invoke(core.clj:2200)
        at boot.user$eval347.invoke(boot.user533829959110297580.clj:13)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.lang.RT$3.invoke(RT.java:318)
        at boot.main$_main$fn__881.invoke(main.clj:139)
        ... 6 more
Caused by: java.lang.IllegalArgumentException: No matching field found: getPath for class clojure.lang.PersistentHashSet
        at clojure.lang.Reflector.getInstanceField(Reflector.java:271)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)
        at boot.file$tree_for$iter__309__313$fn__314.invoke(file.clj:132)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:30)
        at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at boot.file$tree_for.doInvoke(file.clj:131)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at boot.file$sync_BANG_.doInvoke(file.clj:162)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:628)
        at boot.core$run_tasks$sync_BANG___670$fn__671.invoke(core.clj:632)
        at boot.core$run_tasks$sync_BANG___670.invoke(core.clj:631)
        at boot.core$run_tasks$fn__674.invoke(core.clj:637)
        at adzerk.boot_cljs$eval254$fn__255$fn__260$fn__261.invoke(boot_cljs.clj:126)
        at adzerk.boot_cljs$eval230$fn__231$fn__234$fn__235.invoke(boot_cljs.clj:81)
        at boot.core$run_tasks.invoke(core.clj:637)
        at clojure.lang.Var.invoke(Var.java:379)
        at boot.user$eval347$fn__348.invoke(boot.user533829959110297580.clj:13)
        at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
macbook:my-app peterbru$ 
```

**Comment by 23min** [comment]
I removed the ~/.boot directory and /usr/local/bin/boot and reinstalled boot.
I also updated the jamal build.boot file with the latest dependency vectors. 
This seems to have resolved the issue, and even the target directory is created automatically.
