### ISSUE TITLE
Boot.exe: Could not find or load main class: boot.App

### ISSUE THREAD

**Issue by Quasaur** [boot-clj/boot#174]
i was using boot-1.1.1.jar with Hoplon but got tired of the bootstrap.css.map errors...
...so i downloaded the latest boot.exe for Windows.

Now, when i run boot.exe i get the aforementioned error...

...PLEASE HELP ME!!!

**Comment by Quasaur** [comment]
I also get the following error (why would a Windows executable be looking for the Linux 'uname' command?):

Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:551)
        at boot.pod$loading__4958__auto__.invoke(pod.clj:1)
        at boot.pod__init.load(Unknown Source)
        at boot.pod__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.loadClassForName(RT.java:2093)
        at clojure.lang.RT.load(RT.java:430)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.require(ClojureR
untimeShimImpl.java:57)
        at boot.App.newShim(App.java:153)
        at boot.App.aetherShim(App.java:174)
        at boot.App.writeProps(App.java:58)
        at boot.App.readProps(App.java:97)
        at boot.App.main(App.java:301)
Caused by: java.io.IOException: Cannot run program "uname": CreateProcess error=
2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at clojure.java.shell$sh.doInvoke(shell.clj:116)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at boot.util__init.load(Unknown Source)
        at boot.util__init.<clinit>(Unknown Source)
        ... 46 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 51 more

**Comment by micha** [comment]
It looks like you're using boot version 2. The `bootstrap.css.map` errors only occur when you have source maps enabled in your browser---they won't hurt anything. But if you want to you can just add an empty bootstrap.css.map file to silence them.
