### ISSUE TITLE
uber tasks `:as-jars` option broken.

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#264]
I can't get Boot to produce an uberjar that is runnable when setting the `:as-jars` option to `true`.
Exception that's coming up when trying to run the jar looks like this:
```
~/c/minimal-uberjar-case (master=) java -jar target/test.uberjar-0.1.0.jar
Exception in thread "main" java.lang.NoClassDefFoundError: clojure/lang/IFn
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
        at java.lang.Class.getMethod0(Class.java:3010)
        at java.lang.Class.getMethod(Class.java:1776)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: clojure.lang.IFn
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

I created a [minimal case](https://github.com/martinklepsch/minimal-uberjar-case). Behaviour is present with `2.1.2` as well as `master`.

I'm pretty clueless when it comes to Java/Jars/Classpath stuff so any help appreciated. Excluded some obvious error sources like the Clojure jar being excluded by some broken filter but it seems to be present in the built jar:
```
~/c/minimal-uberjar-case (master=) jar tf target/test.uberjar-0.1.0.jar
META-INF/MANIFEST.MF
test/
test/core.clj
META-INF/maven/test.uberjar/test.uberjar/
META-INF/maven/test.uberjar/
META-INF/maven/
META-INF/
META-INF/maven/test.uberjar/test.uberjar/pom.xml
test/uber.clj
test/core__init.class
test/core$loading__4958__auto__.class
test/core.class
test/core$fn__245.class
clojure-1.6.0.jar
test/core$_main.class
META-INF/maven/test.uberjar/test.uberjar/pom.properties
```

**Comment by martinklepsch** [comment]
`:as-jars` is only supposed to work when running the jars in containers which support exploding jars-within-jars. Regular `java -jar` does not have this functionality.

I added a PR to adapt the docstring: #265 .

Also @alandipert experimented with a boot task shipping jars with a custom classloader that explodes jars on startup: https://github.com/adzerk-oss/boot-ubermain
