### ISSUE TITLE
New install error: no checksums available for boot:pod:jar:2.3.0

### ISSUE THREAD

**Issue by sonelliot** [boot-clj/boot#296]
I get this error after running `boot -h` for the first time on my Ubuntu 14.04 machine:

``` bash
Exception in thread "main" org.sonatype.aether.resolution.DependencyResolutionException: Could not transfer artifact boot:pod:jar:2.3.0 from/to clojars (https://clojars.org/repo/): Checksum validation failed, no checksums available from the repository
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke(aether.clj:720)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at cemerick.pomegranate.aether$resolve_dependencies.doInvoke(aether.clj:729)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at boot.aether$resolve_dependencies_STAR_.invoke(aether.clj:75)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$memoize$fn__5097.doInvoke(core.clj:5846)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at boot.aether$resolve_dependencies.invoke(aether.clj:96)
	at boot.aether$resolve_dependency_jars.invoke(aether.clj:112)
	at clojure.lang.Var.invoke(Var.java:394)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:138)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:129)
	at boot.App.resolveDepJars(App.java:216)
	at boot.App.resolveDepJars(App.java:208)
	at boot.App.seedCache(App.java:114)
	at boot.App.readCache(App.java:144)
	at boot.App.main(App.java:347)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact boot:pod:jar:2.3.0 from/to clojars (https://clojars.org/repo/): Checksum validation failed, no checksums available from the repository
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	... 27 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact boot:pod:jar:2.3.0 from/to clojars (https://clojars.org/repo/): Checksum validation failed, no checksums available from the repository
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.sonatype.aether.transfer.ChecksumFailureException: Checksum validation failed, no checksums available from the repository
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:622)
	... 4 more
```

After navigating to https://clojars.org/repo/boot/pod/2.3.0/ I can see that it is indeed missing `pod-2.3.0.jar.sha1` and `pod-2.3.0.jar.md5` files. 

I am going to attempt to build from source. It looks like the `pod-2.3.1` checksums are available.

**Comment by alandipert** [comment]
Thanks for the report.  I think @micha experienced connectivity problems in the middle of a deployment, and so artifacts on Clojars are not in a good state.  @tobias has volunteered to help us fix things up, and so this will likely be resolved very soon.

**Comment by tobias** [comment]
I fixed the issues with `maven-metadata.xml` for `boot/worker`, but didn't realize the sums were missing for this version of `boot/pod` as well. @alandipert @micha: can one of you give me the sha1 and md5 for pod-2.3.0.jar? I can then verify that the artifact on the server matches, and place the sums there.

**Comment by sonelliot** [comment]
Thanks for the quick replies @alandipert @tobias. Building from source seemed to work for me in the meantime.

**Comment by alandipert** [comment]
@tobias `8ac2117748272c4498c1d46c2d8c9d1fcb969bc5` is the sha1sum and [this is the pod-2.3.0.jar](https://dl.dropboxusercontent.com/u/12379861/pod-2.3.0.jar) that should be up there.  Thanks for helping!

**Comment by tobias** [comment]
I've updated the jar and checksums. Please give it a try now.

**Comment by pleasetrythisathome** [comment]
fixed for me!

**Comment by alandipert** [comment]
@sonelliot please do close if it this is fixed for you also, thanks!

**Comment by alandipert** [comment]
Pretty sure this is fixed, please do reopen if not.
