### ISSUE TITLE
Boot fails with java.lang.ClassNotFoundException: org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl

### ISSUE THREAD

**Issue by prasincs** [boot-clj/boot#323]
I'm running OSX 10.11 and I installed boot using the following command 
    brew install boot-clj
which has worked in the past but I'm getting the error below when I try to run boot

$boot repl -h
```
Exception in thread "main" java.lang.RuntimeException: Failed to load ClojureRuntimeImpl
        at org.projectodd.shimdandy.ClojureRuntimeShim.newRuntime(ClojureRuntimeShim.java:21)
        at org.projectodd.shimdandy.ClojureRuntimeShim.newRuntime(ClojureRuntimeShim.java:32)
        at boot.App.newShim(App.java:154)
        at boot.App.aetherShim(App.java:183)
        at boot.App.writeProps(App.java:60)
        at boot.App.readProps(App.java:103)
        at boot.App.main(App.java:329)
Caused by: java.lang.ClassNotFoundException: org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.projectodd.shimdandy.ClojureRuntimeShim.newRuntime(ClojureRuntimeShim.java:18)
        ... 6 more
```

Java version info 

```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by prasincs** [comment]
I just tried compiling the version from master on the same machine and I'm not running into the issue anymore in that case. The version in homebrew might be the culprit in this case.

**Comment by martinklepsch** [comment]
@prasincs thanks for the report 👍

Can you share the output of `boot -V` for your homebrew installation? Thanks!

**Comment by micha** [comment]
Homebrew package is out of date, it should install the version from https://github.com/boot-clj/boot-bin.
