### ISSUE TITLE
boot should use temporary files when downloading boot jars

### ISSUE THREAD

**Issue by schmir** [boot-clj/boot#324]
Hitting Ctrl-C while boot downloads boot.jar results in a broken
installation. boot should try to detect a broken boot.jar and/or
download to a temporary file.

    (local) ~/bin % ./boot -V
    Downloading https://github.com/boot-clj/boot/releases/download/2.4.2/boot.jar...^C%                                                                130 (local) ~/bin % ./boot -V
    Exception in thread "main" java.lang.ClassNotFoundException: boot.App
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	    at java.lang.Class.forName0(Native Method)
	    at java.lang.Class.forName(Class.java:348)
	    at boot.Loader.main(Loader.java:231)
    1 (local) ~/bin % ./boot -V
    Exception in thread "main" java.lang.ClassNotFoundException: boot.App
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	    at java.lang.Class.forName0(Native Method)
	    at java.lang.Class.forName(Class.java:348)
	    at boot.Loader.main(Loader.java:231)

**Comment by martinklepsch** [comment]
We could add a `boot.jar.shasum` thing to each release download the files to a tmpdir, compare & copy.

**Comment by schmir** [comment]
shasum may be a bit of overkill. I think having boot check that boot.jar is a valid jar file suffices. Being able to list the contents of the jar file should be enough to check for validity since that would detect truncated files.

**Comment by DangerousYams** [comment]
how do I re-install or clean up the broken install? I tried brew uninstall boot-clj and reinstalling it but it has the same issue

**Comment by martinklepsch** [comment]
@DangerousYams try `rm -rf ~/.boot/cache/bin/` — assuming you didn't set `$BOOT_HOME` to something other then `~/.boot` :)
