### ISSUE TITLE
Issue downloading boot.jar

### ISSUE THREAD

**Issue by emiln** [boot-clj/boot#335]
I just downloaded the latest boot.sh version 2.4.2 from the boot-bin project and now I'm getting a ConnectionException when attempting to run boot. I've been using boot version 2.0.0 (maybe a release client, can't quite recall) for a while, and decided to upgrade to the latest version. I deleted the old `boot` executable and just downloaded the latest one.

This is the exception I'm seeing:

```
$ boot -h
Downloading https://github.com/boot-clj/boot/releases/download/2.4.2/boot.jar...Exception in thread "main" java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1037)
	at boot.Loader.download(Loader.java:169)
	at boot.Loader.install(Loader.java:182)
	at boot.Loader.main(Loader.java:219)
```

Accessing the file in Firefox works just fine. The strange thing is that no proxy settings or anything have changed since I last used Boot 2.0.0 (just yesterday).

Do you have any idea what could be wrong?

**Comment by micha** [comment]
Is this still happening?

**Comment by emiln** [comment]
Sorry for the slow response. I had to wait until I was back at the specific computer (at work) that exhibits the issue. Yes, it's still happening, but _only_ here at work. I have no issues at home, so I suspect it's a network issue due to our many reverse proxies and what have you.

**Comment by micha** [comment]
You probably already know about this but just in case: http://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm

You can add the options to `BOOT_JVM_OPTIONS` env var.

**Comment by emiln** [comment]
That did the trick! Specifically, I edited the file `~/.boot/boot.properties` to contain the following:

```
#Thu Dec 10 10:45:48 CET 2015
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_VERSION=2.4.2
BOOT_CLOJURE_VERSION=1.7.0
BOOT_JVM_OPTIONS=-Dhttp.proxyHost=my-host -Dhttp.proxyPort=my-port -Dhttps.proxyHost=my-host -Dhttps.proxyPort=my-port
```

That seems to cover all the bases for getting boot running behind my company proxy. Putting the settings in `~/.boot/boot.properties` avoids having to set them for all projects. Thanks for your help, @micha. I'm closing this and leaving behind my fix.

**Comment by Bost** [comment]
@emiln specifying proxy in BOOT_JVM_OPTIONS doesn't work for me :(

**Comment by jiyinyiyong** [comment]
what should I put it please!!

**Comment by jiyinyiyong** [comment]
```
~/.boot/cache/bin/<version>/
```
