### ISSUE TITLE
S3 Private Wagon Snapshot

### ISSUE THREAD

**Issue by charlesg3** [boot-clj/boot#342]
I'm having a bit of trouble trying to get boot to pull in a dependency from a private wagon that is stored on S3.

Here's a copy of the `boot.build` file (with any credentials or relevant info redacted). 

```
(def aws-creds {:access-key (System/getenv "AWS_ACCESS_KEY_ID")
                :secret-key (System/getenv "AWS_SECRET_ACCESS_KEY")})

(set-env! :dependencies '[[my/repo "0.3.1-SNAPSHOT"]]]
          :wagons       '[[s3-wagon-private "1.1.2"]]

          :repositories #(concat % [["snapshots" {:url "s3p://my.jars/snapshots/"
                                                             :passphrase (:secret-key aws-creds)
                                                             :username (:access-key aws-creds)
                                                             :releases false}]
                                   ["releases" {:url "s3p://my.jars/releases/"
                                                            :passphrase (:secret-key aws-creds)
                                                            :username (:access-key aws-creds)
                                                            :snapshots false}]]))
```

Here's a snippet of the output where it's failing (with portions redacted):

```
Aether: {:type :initiated,
 :method :get,
 :transferred 0,
 :error nil,
 :data-buffer nil,
 :data-length 0,
 :resource
 {:repository "s3p://my.project/snapshots/",
  :name "my/project/0.3.1-SNAPSHOT/product-0.3.1-SNAPSHOT.pom",
  :file nil,
  :size -1,
  :transfer-start-time 1447373063764,
  :trace
  #object[org.sonatype.aether.util.DefaultRequestTrace 0x78bf4e5b "my:project:pom:0.3.1-SNAPSHOT < [#object[org.sonatype.aether.repository.RemoteRepository 0x707194ba \"clojars (https://clojars.org/repo/, releases+snapshots)\"]
 #object[org.sonatype.aether.repository.RemoteRepository 0x1190200a \"maven-central (https://repo1.maven.org/maven2/, releases+snapshots)\"] #object[org.sonatype.aether.repository.RemoteRepository 0x6a2f6f80 \"thinktopic-snapsh
ots (s3p://thinktopic.jars/snapshots/, snapshots)\"] #object[org.sonatype.aether.repository.RemoteRepository 0x45b4c3a9 \"thinktopic-releases (s3p://thinktopic.jars/releases/, releases)\"]]"]}}

Nov 12, 2015 5:04:24 PM org.jets3t.service.impl.rest.httpclient.RestS3Service performRequest
WARNING: Error Response: HEAD '/snapshots%2Fcn%2Fproduct%2F0.3.1-SNAPSHOT%2Fproduct-0.3.1-SNAPSHOT.pom' -- ResponseCode: 404, ResponseStatus: Not Found, Request Headers: [Content-Type: , Date: Fri, 13 Nov 2015 00:04:23 GMT, Aut
horization: AWS AKIAJZJ5BDREDACTEDOlIvIuBJRv8HLlNxSpFgvgE=, User-Agent: JetS3t/0.7.1 (Linux/3.19.0-31-generic; amd64; en; JVM 1.8.0_45-internal), Host: thinktopic.jars.s3.amazonaws.com], Response Headers: [x-amz-request-
id: C6CAC7F0EF661BA2, x-amz-id-2: +7SnPuREDACTEDM5BOMRbzE=, Content-Type: application/xml, Transfer-Encoding: chunked, Date: Fri, 13 Nov 2015 00:04:23 GMT, Server: AmazonS3]
Nov 12, 2015 5:04:24 PM org.jets3t.service.impl.rest.httpclient.RestS3Service performRequest
SEVERE: Request Failed.
org.jets3t.service.S3ServiceException: Request Error. HEAD '/snapshots%2Fcn%2Fproduct%2F0.3.1-SNAPSHOT%2Fproduct-0.3.1-SNAPSHOT.pom' on Host 'thinktopic.jars.s3.amazonaws.com' @ 'Fri, 13 Nov 2015 00:04:23 GMT' -- ResponseCode: 
404, ResponseStatus: Not Found, RequestId: C6CAC7F0EF661BA2, HostId: +7REDACTEDDkwa/uqM82mrX9bVL/0d2Fhr96QujFgSpHWnLn4dMREDACTED5BOMRbzE=
        at org.jets3t.service.impl.rest.httpclient.RestS3Service.performRequest(RestS3Service.java:502)
        at org.jets3t.service.impl.rest.httpclient.RestS3Service.performRestHead(RestS3Service.java:842)
        at org.jets3t.service.impl.rest.httpclient.RestS3Service.getObjectImpl(RestS3Service.java:1710)
        at org.jets3t.service.impl.rest.httpclient.RestS3Service.getObjectDetailsImpl(RestS3Service.java:1646)
        at org.jets3t.service.S3Service.getObjectDetails(S3Service.java:2130)
        at org.jets3t.service.S3Service.getObjectDetails(S3Service.java:1446)
        at org.springframework.aws.maven.SimpleStorageServiceWagon.doesRemoteResourceExist(SimpleStorageServiceWagon.java:77)
        at org.springframework.aws.maven.AbstractWagon.resourceExists(AbstractWagon.java:290)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:577)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.jets3t.service.impl.rest.HttpException
        at org.jets3t.service.impl.rest.httpclient.RestS3Service.performRequest(RestS3Service.java:500)
        ... 12 more
```

It seems as though it isn't following the usual snapshots protocol of looking at the `maven-metadata.xml` file to determine the actual path of the snapshot. I can verify that the credentials are valid and that I can find this particular file. Please let me know if there's any other information I should provide.

**Comment by micha** [comment]
I think I'd have to be able to reproduce this to be of any help, as there are many things that could be going wrong.

**Comment by charlesg3** [comment]
We're going a different route for now to deal with this. Closing now for lack of better telemetry.
