### ISSUE TITLE
boot.sh seems to be pointing to an old link, not installing

### ISSUE THREAD

**Issue by hierophantos** [boot-clj/boot#344]
Tried to both manually download and run from `/usr/local/bin` per instructions as well as with Homebrew. 

Get the following error on both:

`Downloading https://github.com/boot-clj/boot/releases/download/2.0.0-rc6/boot.jar...Exception in thread "main" java.io.FileNotFoundException: https://github.com/boot-clj/boot/releases/download/2.0.0-rc6/boot.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1038)
	at boot.Loader.download(Loader.java:169)
	at boot.Loader.install(Loader.java:182)
	at boot.Loader.main(Loader.java:219)`

**Comment by micha** [comment]
@hierophantos can you please remove your `~/.boot/cache` directory and try again?

**Comment by hierophantos** [comment]
Thank you! `rm -rf ~/.boot/` worked for me!
