### ISSUE TITLE
Can't install boot on Linux

### ISSUE THREAD

**Issue by r0man** [boot-clj/boot#351]
I can't install the latest boot on Linux. Looks like the JAR file doesn't exists that gets downloaded by the bash script.

```
[roman@bombaclaat bin]$ curl -L https://github.com/boot-clj/boot-bin/releases/download/2.4.2/boot.sh > boot; chmod 755 boot
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   583    0   583    0     0   1206      0 --:--:-- --:--:-- --:--:--  1209
100  6389  100  6389    0     0   6312      0  0:00:01  0:00:01 --:--:-- 1039k
[roman@bombaclaat bin]$ ./boot 
Downloading https://github.com/boot-clj/boot/releases/download/2.0.0-rc12/boot.jar...Exception in thread "main" java.io.FileNotFoundException: https://github.com/boot-clj/boot/releases/download/2.0.0-rc12/boot.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1038)
        at boot.Loader.download(Loader.java:175)
        at boot.Loader.install(Loader.java:219)
        at boot.Loader.main(Loader.java:238)
[roman@bombaclaat bin]$ 
```

**Comment by martinklepsch** [comment]
@r0man you're using a very old version of boot (2.0 RC12).

Most likely this is specified by either `~/boot/boot.properties` or `~/.boot/cache/boot.properties`. Easiest solution is just to delete those files.

**Comment by r0man** [comment]
Hey @martinklepsch, I deleted ~/.boot and it worked. Thanks, boot noob over here :)

**Comment by martinklepsch** [comment]
@r0man awesome! have fun! :tada:

**Comment by escherize** [comment]
Thanks guys, this helped me too.
