### ISSUE TITLE
Trying to install but can't

### ISSUE THREAD

**Issue by phillord** [boot-clj/boot#369]
I've been trying to install boot. I've had this working before, but upgrading broke. So I've installed the latest linked from the website (2.4.2 ironically). Running this gives me this error:

Downloading https://github.com/boot-clj/boot/releases/download/2.0.0-pre18/boot.jar...Exception in thread "main" java.io.FileNotFoundException: https://github.com/boot-clj/boot/releases/download/2.0.0-pre18/boot.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1041)
	at boot.Loader.download(Loader.java:175)
	at boot.Loader.install(Loader.java:219)
	at boot.Loader.main(Loader.java:238)

**Comment by Deraen** [comment]
You have a old `boot.properties` file referring to very old boot version at either `~/.boot/boot.properties` or `~/.boot/cache/boot.properties`. Remove it.

**Comment by micha** [comment]
You could try downloading the latest version of `boot.sh` here: https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh ... I just pushed a new version there.

**Comment by phillord** [comment]
Yes, you are right! I have the latest version downloaded now. Thanks for the rapid response.
