### ISSUE TITLE
Avoid printing the stacktrace with exit-error

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot#405]
For my parallel testing patch I decided to exit using `exit-error` as suggested.

The problem is that `boot` always prints the stacktrace if you exit this way and this looks a bit ugly while exiting from the tests (we just need a summary).

At the moment the `App.Exit` exception is used to carry information down the boot stack and my idea was to use the same machinery. I can tranform the `App.Exit` message in an `edn` *string* and pass something like: `{:return-code 1 :print-stack-trace? false}`. Of course true will be the default.

Do you guys like it or can you suggest a better way?

**Comment by arichiardi** [comment]
So I was able to catch and print the trace of the unwanted exception:

```
clojure.lang.ExceptionInfo: boot.App$Exit: {:stack-trace? true, :code 1}
 {:file "/tmp/boot.user6239531196785232534.clj", :line 19}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at boot.main$_main$fn__1195.invoke(main.clj:207)
	at boot.main$_main.invoke(main.clj:200)
	at clojure.lang.Var.invoke(Var.java:394)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:159)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:150)
	at boot.App.runBoot(App.java:399)
	at boot.App.main(App.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Boot.main(Boot.java:258)
Caused by: java.util.concurrent.ExecutionException: boot.App$Exit: {:stack-trace? true, :code 1}

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at clojure.core$deref_future.invoke(core.clj:2180)
	at clojure.core$future_call$reify__6320.deref(core.clj:6420)
	at clojure.core$deref.invoke(core.clj:2200)
	at boot.core$boot.doInvoke(core.clj:869)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at boot.user$eval553.invoke(boot.user6239531196785232534.clj:21)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.lang.RT$3.invoke(RT.java:318)
	at boot.main$_main$fn__1195.invoke(main.clj:200)
	... 11 more
Caused by: boot.App$Exit: {:stack-trace? true, :code 1}

	at boot.task_helpers$fn__1467$fn__1468$fn__1474$fn__1475$fn__1476.invoke(task_helpers.clj:265)
	at boot.task_helpers$fn__1467$fn__1468$fn__1474$fn__1475.invoke(task_helpers.clj:265)
	at boot.task_helpers$fn__1423$fn__1424$fn__1430$fn__1431.invoke(task_helpers.clj:246)
	at boot.task_helpers$fn__1347$fn__1348$fn__1354$fn__1355.invoke(task_helpers.clj:193)
	at boot.task_helpers$fn__1383$fn__1384$fn__1390$fn__1391.invoke(task_helpers.clj:199)
	at boot.task.built_in$fn__2697$fn__2698$fn__2706$fn__2707.invoke(built_in.clj:844)
	at boot.task.built_in$fn__2697$fn__2698$fn__2706$fn__2707.invoke(built_in.clj:844)
	at boot.task.built_in$fn__2697$fn__2698$fn__2706$fn__2707.invoke(built_in.clj:844)
	at boot.task.built_in$fn__2697$fn__2698$fn__2706$fn__2707.invoke(built_in.clj:844)
	at boot.task.built_in$fn__2697$fn__2698$fn__2706$fn__2707.invoke(built_in.clj:844)
	at boot.task.built_in$fn__2697$fn__2698$fn__2706$fn__2707.invoke(built_in.clj:844)
	at boot.core$run_tasks.invoke(core.clj:862)
	at boot.core$boot$fn__947.invoke(core.clj:872)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

From a first analysys, it looks like it is because I am throwing an exception from `exit-error` but I am inside a `future`. The exception is wrapped then and of course it is not a `boot.App$Exit` anymore.

**Comment by seancorfield** [comment]
From Slack:

There are multiple use cases here:

1. Argument validation error feels like "exit immediately with a message and status 1" (since this sort of error shouldn't even allow tasks to run in my opinion).
1. Exit OK should short-circuit execution of the task but let a pipeline continue (or let the top-level just exit cleanly with no stacktrace and status 0).
1. A "real" exception which should print a stack trace if it hits the top-level (but can be caught and swallowed / handled by another task).
1. An "error" which should exit the task in a way that other tasks could catch and handle, but the top-level should just exit with status 1 but no stack trace.

**Comment by arichiardi** [comment]
This turned out to be a bug and before any other consideration we should probably merge it first. PR #407

**Comment by seancorfield** [comment]
PR #407 seems to be a lot more changes than just unpeeling exceptions... Is it a pull against the wrong branch?
