### ISSUE TITLE
In emacs, temp files cause boot 2.6.0-SNAPSHOT to fail

### ISSUE THREAD

**Issue by levitanong** [boot-clj/boot#438]
In emacs, when editing a file, it creates a duplicate of that file.

e.g.
Given `index.cljs.hl`, it will create `.#index.cljs.hl`.

To reproduce:
1. While boot is running, edit two files. Do not save.
2. Save one. This will cause boot to recompile
3. Watch boot explode

`Exception in thread "Thread-17" java.nio.file.NoSuchFileException: path/to/proj/.#index.cljs.hl`

**Comment by micha** [comment]
It's tricky to deal with those kinds of changes in the filesystem, like automated things creating and deleting files all over the place. Can you get a stack trace?

The best workaround is to configure the editor to store backup files in its own directory (there are [instructions for how to do this in Vim][1] in the wiki, perhaps we could add this to [the Emacs article][2], too).

The second-best workaround is to have boot ignore those files. To do this you can create a file named `.bootignore` in the project directory with the following contents:

_.bootignore_
```
(^|/)\.#[^/]+$
```

[1]: https://github.com/boot-clj/boot/wiki/For-Vim-Users
[2]: https://github.com/boot-clj/boot/wiki/For-Emacs-Users

**Comment by levitanong** [comment]
Here is the stack trace

```
Exception in thread "Thread-17" java.nio.file.NoSuchFileException: src/hl/peak/.#index.cljs.hl
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.getLastModifiedTime(Files.java:2266)
	at boot.filesystem$mkvisitor$fn__728.invoke(filesystem.clj:83)
	at boot.filesystem.proxy$java.nio.file.SimpleFileVisitor$ff19274a.visitFile(Unknown Source)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at boot.filesystem$mktree.doInvoke(filesystem.clj:95)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at boot.core$patch_BANG_$merge_SINGLEQUOTE___739.invoke(core.clj:578)
	at clojure.core.protocols$iter_reduce.invoke(protocols.clj:49)
	at clojure.core.protocols$fn__6510.invoke(protocols.clj:112)
	at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6519)
	at boot.core$patch_BANG_.doInvoke(core.clj:580)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at boot.core$sync_user_dirs_BANG_.invoke(core.clj:138)
	at boot.core$set_user_dirs_BANG_$on_change__475.invoke(core.clj:176)
	at boot.core$watch_dirs$fn__748.invoke(core.clj:607)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:745)
```

I can research on how to get emacs to store the backup files elsewhere. Why is this the best workaround though? It seems like adding that regex to `.bootignore` is more preferrable.

**Comment by micha** [comment]
Thanks for getting the stack trace. I will have a look and see what can be done. Is this a regression, by the way? Does this issue not apply to boot version 2.5.5 for example?

Adding a `.bootignore` will cause boot to do more work, because it needs to filter all the files. It's not a lot of overhead but little things start adding up if you have a lot of files. Also just in general I like having my editor store backup files elsewhere in case I want to make a tarball for example or something like that. Or if I use a different editor I'd have to have it ignore those... things like that.

**Comment by levitanong** [comment]
Yeah, this is not an issue on 2.5.5

re: `.bootignore` ah, that makes sense! Thanks for the explanation. :)

**Comment by micha** [comment]
Ok cool, I think I have a fix, testing now.

**Comment by levitanong** [comment]
Thanks man :D

**Comment by Chris-Andrews** [comment]
I had a problem with emacs temp files causing errors as well and found this thread. In case anyone has trouble with this on Windows, I had to modify the regex to:
`(^|(/|\\))\.#[^(/|\\)]+$`
