### ISSUE TITLE
brew version does not work

### ISSUE THREAD

**Issue by krzychukula** [boot-clj/boot#467]
> brew upgrade boot-clj
Error: boot-clj 2.5.2 already installed
> boot cljs
Please download latest Boot binary: https://github.com/boot-clj/boot#install

**Comment by krzychukula** [comment]
➜  boot -u
Retrieving boot-2.6.0.jar from https://clojars.org/repo/
#https://github.com/boot-clj/boot
#Wed May 25 11:52:11 CEST 2016
BOOT_CLOJURE_VERSION=1.7.0
BOOT_VERSION=2.6.0
#App version: 2.2.0
Retrieving pod-2.6.0.jar from https://clojars.org/repo/
Retrieving core-2.6.0.jar from https://clojars.org/repo/
Retrieving aether-2.6.0.jar from https://clojars.org/repo/
Retrieving worker-2.6.0.jar from https://clojars.org/repo/
Retrieving jsoup-1.7.2.jar from https://repo1.maven.org/maven2/
Retrieving commons-lang-2.6.jar from https://repo1.maven.org/maven2/
Retrieving commons-io-2.2.jar from https://repo1.maven.org/maven2/
Retrieving wagon-http-2.9.jar from https://repo1.maven.org/maven2/
Retrieving httpclient-4.3.5.jar from https://repo1.maven.org/maven2/
Retrieving wagon-http-shared-2.9.jar from https://repo1.maven.org/maven2/
Retrieving commons-logging-1.1.3.jar from https://repo1.maven.org/maven2/
Retrieving httpcore-4.3.2.jar from https://repo1.maven.org/maven2/
➜  boot -h
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Boot.main(Boot.java:258)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: boot.App.config(Ljava/lang/String;)Ljava/lang/String;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at boot.App.runBoot(App.java:248)
	at boot.App.main(App.java:356)
	... 5 more
Caused by: java.lang.NoSuchMethodError: boot.App.config(Ljava/lang/String;)Ljava/lang/String;
	at boot.util$colorize_QMARK__system_default.invoke(util.clj:29)
	at boot.util__init.load(Unknown Source)
	at boot.util__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at boot.pod$loading__4958__auto__.invoke(pod.clj:1)
	at boot.pod__init.load(Unknown Source)
	at boot.pod__init.<clinit>(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at clojure.lang.RT.loadClassForName(RT.java:2182)
	at clojure.lang.RT.load(RT.java:436)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.require(ClojureRuntimeShimImpl.java:78)
	at boot.App.newShim(App.java:162)
	at boot.App$1.call(App.java:223)
	at boot.App$1.call(App.java:221)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
^C%                                                                                                                                                                             
➜  java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by Deraen** [comment]
Your Boot binary is quite old: #App version: 2.2.0

Try updating Brew repository and Boot package. As far as I remember, Brew doesn't do automatic updates.

**Comment by krzychukula** [comment]
`rm -rf .boot` helped. Thanks!
