### ISSUE TITLE
java.nio.file.NoSuchFileException when trying to copy non-existing file

### ISSUE THREAD

**Issue by skammer** [boot-clj/boot#477]
Tools like ImageOptim create a bunch of short-lived files when performing optimizations. This causes `watch` error out with an exception and stop responding entirely:

```
Exception in thread "Thread-14" java.nio.file.NoSuchFileException: resources/public/img/.apple-touch-icon-72x72~imageoptim.png
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
        at boot.filesystem$copy_BANG_.invoke(filesystem.clj:150)
        at boot.filesystem$patch_BANG_.doInvoke(filesystem.clj:179)
        at clojure.lang.RestFn.invoke(RestFn.java:494)
        at boot.core$patch_BANG_.doInvoke(core.clj:661)
        at clojure.lang.RestFn.invoke(RestFn.java:464)
        at boot.core$sync_user_dirs_BANG_.invoke(core.clj:139)
        at boot.core$set_user_dirs_BANG_$on_change__475.invoke(core.clj:190)
        at boot.core$watch_dirs$fn__748.invoke(core.clj:687)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by schmir** [comment]
Wouldn't that issue justify a 2.6.1 release?
