### ISSUE TITLE
Boot fails to start on Tumbleweed with Java 9

### ISSUE THREAD

**Issue by ghost** [boot-clj/boot#637]
# Boot Bug Report

## Platform details

Platform (macOS, Linux, Windows): Linux
Platform version: openSUSE Tumbleweed
JRE/JDK version (`java -version`): `openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.abuild.jdk9-252475ccfd84)
OpenJDK 64-Bit Server VM (build 9-internal+0-adhoc.abuild.jdk9-252475ccfd84, mixed mode)`

## Boot details

Boot version (2.7.1): 2.7.2
`build.boot` present? (yes/no): no
`~/.boot/profile` present? (yes/no): no
Task name? (if applicable): any

### `build.boot` content (if applicable)

```clojure
;; build.boot content here
```

### `~/.boot/profile` content (if applicable)

```clojure
;; ~/.boot/profile content here
```

## Description

`boot -h
Downloading https://github.com/boot-clj/boot/releases/download/2.5.2/boot.jar...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(Unknown Source)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Unknown Source)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<clinit>(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl.access$100(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.security.Provider$Service.getImplClass(Unknown Source)
	at java.base/java.security.Provider$Service.newInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getDefault(Unknown Source)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
	at java.base/java.net.URL.openConnection(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at Boot.download(Boot.java:173)
	at Boot.install(Boot.java:224)
	at Boot.main(Boot.java:250)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(Unknown Source)
	... 29 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(Unknown Source)
	at java.base/javax.crypto.JceSecurity.access$000(Unknown Source)
	at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
	at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	... 30 more
`

## Steps to reproduce

Download `boot.sh`, make it executable, run for the first time with no `~/.boot` present on openSUSE Tumbleweed with Java 9.

**Comment by martinklepsch** [comment]
The interesting part of the stacktrace seems to be:
```
Can't read cryptographic policy directory: unlimited
```
Maybe this is related? https://github.com/docker-library/openjdk/issues/101

Could you paste the values of `$JAVA_HOME` and `$JAVA_SECURITY_DIR`? 

Hope this helps.

**Comment by flyboarder** [comment]
Closing as stale. If this is still a problem, please reopen with updated information.
