### ISSUE TITLE
Boot 2.7.0+ incompatible with Java 7

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#677]
```sh
$ java -version # java version "1.7.0_80"

$ BOOT_VERSION=2.7.0 boot -d clj-time

Could not transfer artifact boot:pod:pom:2.7.0 from/to clojars (https://repo.clojars.org/): Received fatal alert: protocol_version
[...]
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
        at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
        ... 9 more
```

This seems related: https://stackoverflow.com/questions/33595021/getting-javax-net-ssl-sslexception-received-fatal-alert-protocol-version-while

Not sure if this should be considered a Boot issue but the README states JDK 7+ are supported so I guess the options are dropping support and figuring out why this isn't working anymore.

**Comment by martinklepsch** [comment]
This works (via https://github.com/technomancy/leiningen/issues/2364):
```sh
env BOOT_VERSION=2.7.0 BOOT_JVM_OPTIONS=-Dhttps.protocols=TLSv1.2 boot -d clj-time
```

**Comment by tobias** [comment]
The reason this appeared in boot 2.7.0 is we switched the default url that boot uses for clojars from `https://clojars.org/repo` (served by the clojars.org server) to `https://repo.clojars.org` (a CDN provided by Fastly). Unfortunately, Fastly only supports TLS 1.2. So another possible workaround until this is resolved is to use the old repo by overriding the url for clojars, which I think you can do with:

```
(set-env!
  :repositories  
         [["central" {:url "https://repo1.maven.org/maven2" :snapshots false}]
          ["clojars" {:url "https://clojars.org/repo"}]])
```

**Comment by martinklepsch** [comment]
One way to fix this could be to conditionally use the clojars.org server if we're on Java 7.  
```java
System.getProperty("java.version")
```

**Comment by Deraen** [comment]
What about just documenting that we require Java 8?

**Comment by martinklepsch** [comment]
Yeah not fixing it definitely is an option and people who need Java 7 could still use the workaround of passing additional JVM OPTS. Hard to judge if there are many Boot users still on Java 7.

**Comment by alandipert** [comment]
I think we can say we require Java 8 now.
