### ISSUE TITLE
NullPointerException when trying to run shebang boot script on macOS

### ISSUE THREAD

**Issue by caleb** [boot-clj/boot#758]
On two different machines running macOS Catalina 10.15.1 I get a NullPointerException when trying to run boot "shebang" scripts.

I've tried Oracle JDK 11, 12, and 13, and OpenJDK 13.

Inside a docker container the scripts run as expected. This also used to run on macOS a couple months ago. I will try a fresh Catalina install in a VM to make sure it is not a result of having upgraded from Mojave (10.14) on both of my Macs. I will post an update once I'm able to do that.

Here is such a script:

```clojure
#!/usr/bin/env boot

(print "Hello world")
```

Here is the error I get:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Boot failed to start:
java.lang.NullPointerException
	at boot.main$shebang_QMARK_.invokeStatic(main.clj:114)
	at boot.main$shebang_QMARK_.invoke(main.clj:110)
	at boot.main$_main.invokeStatic(main.clj:140)
	at boot.main$_main.invoke(main.clj:123)
	at clojure.lang.Var.invoke(Var.java:399)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:154)
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke(ClojureRuntimeShimImpl.java:145)
	at boot.App.runBoot(App.java:407)
	at boot.App.main(App.java:500)
```

**To Reproduce**
1. Open a terminal
2. Run the above script `./hello.clj`
3. See error

**Expected behavior**
It should print "Hello world"

** Versions:**
 - OS: macOS 10.15.1 (Catalina)
 - java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
 - cat ~/.boot/boot.properties
#http://boot-clj.com
#Sun Dec 01 22:17:29 EST 2019
BOOT_VERSION=2.8.3
BOOT_CLOJURE_VERSION=1.10.1
BOOT_CLOJURE_NAME=org.clojure/clojure

**Comment by caleb** [comment]
Okay, I've tested this on a fresh install of Catalina and I get the same error.

I installed `boot-clj` and `oracle-jdk` from home-brew and home-brew cask respectively.

**Comment by flyboarder** [comment]
I believe this is caused by a missing property "boot.app.path" as per the stack trace.

**Comment by flyboarder** [comment]
I can also confirm the above script works on `10.14.6`

**Comment by caleb** [comment]
That’s what I figured too, and I’ve done some more experiments by installing Mojave, and High Sierra and I am getting the same issue.

I don’t know what changed. I’ve been using these scripts for years on different machines without ever seeing this.

Maybe the boot wrapper program has changed?

From a clean VM I’m doing:

```
$ xcode-select —install
$ <install home brew>
$ brew cask install oracle-jdk 
$ brew install boot-clj
$ ./hello.clj
```

It seems like the boot wrapper is supposed to set `boot.app.path` but it isn’t getting set like you said.

I’ll do some more tests later.

**Comment by caleb** [comment]
Okay, I've tracked this down to a bug with the homebrew installation of boot. When installed manually boot works.

Now to track down what changed in the homebrew formula
